### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by Kru83** [sedelmeyer/family-genealogy-database#1]
Hi,  I am working on setting up Family Tree Database Model.  I wanted to see if you had sample data that you can share?  I am just trying to figure out how some of the relationships are tired together.

Example: Two Kids and their parents.

**Comment by Kru83** [comment]
I think i figured it out.

**Comment by Kru83** [comment]
Not required.

**Comment by sedelmeyer** [comment]
Sorry, but I don't have sample data on hand. I haven't revisited this project in some time. I am glad you were able to figure it out. If any other questions/issues come up, let me know.

**Comment by Kru83** [comment]
Thanks for the following up.  I am chugging along, that diagram is a huge help.
